### ISSUE TITLE
RTON Decode Bug

### ISSUE THREAD

**Issue by Tre-VN** [twinkles-twinstar/TwinStar.ToolKit#5] opened 2023-02-17 09:12 UTC
So I was decoding RTON using TwinStar.ToolKit ~ Cli core 26 script 30 shell 26 and this happen, it appear that there is some unknown charset in the RTON file. Here is that RTON file: https://msconfigs-my.sharepoint.com/:u:/g/personal/harumavn963_365_sfc_edu_vn/Ecj6Bdv4j0lCrERwZS08bksB1otdNyUMvUMOfZfzJ0uVzQ?e=aZ5Apq

It seem like this is the bug with the tool decoding system, the game still working normally with this.

![image](https://user-images.githubusercontent.com/114157573/219601872-cfa0e636-327c-4634-88f2-b9f9487a890c.png)

**Comment by twinkles-twinstar** [comment] 2023-02-17 10:21
This RTON has an implicit RTID logic error, and the tool does have something that should be modified. Where does it come from? Below is the file I decoded.
[PLANTTYPES.zip](https://github.com/twinkles-twinstar/TwinStar.ToolKit/files/10765705/PLANTTYPES.zip)

**Comment by Tre-VN** [comment] 2023-02-17 10:23
It come from this RSB: https://drive.google.com/drive/folders/135ybF7p_azg1TcncLesBcf2XDZVqGBUZ

There are some PAMs are broken in the RSB too if I remember correctly, here is one example: 
https://msconfigs-my.sharepoint.com/:u:/g/personal/harumavn963_365_sfc_edu_vn/ESYEbX0v7-pEur2EJsJJQOkBlwDG8pC7_7wGTkQHlmDo6g?e=I2yEai

![image](https://user-images.githubusercontent.com/114157573/219618287-4eea9d1a-78e2-4ecb-8d35-0bec72538094.png)

**Comment by twinkles-twinstar** [comment] 2023-02-17 10:27
this is official's rsb, or not ?

**Comment by Tre-VN** [comment] 2023-02-17 10:29
this is modified rsb from a mod, you should repair it first, it was corrupted by Taiji Disturb.

**Comment by twinkles-twinstar** [comment] 2023-02-17 11:34
There is no error in pam in rsb. The failure to decode the pam provided by you is caused by a structure error. The game can run normally because it has a certain fault tolerance, but the tool strictly throws an exception for any error. This behavior will not Change.

**Comment by Tre-VN** [comment] 2023-02-17 11:38
Thank you for that explaination, will you fix the RTON Decode?

**Comment by twinkles-twinstar** [comment] 2023-02-17 11:43
Perhaps, the fix for this possibly wrong logic needs some testing to let me judge that this is indeed a bug, but I don't have time to test it at the moment, please keep this issue open, I will finish the test or fix it then close.

**Comment by twinkles-twinstar** [comment] 2023-02-17 11:46
Before I decide whether to solve this problem, you can modify and compile `Core/core/tool/popcap/rton/encode.hpp` yourself to solve the decoding error at runtime.
![Snipaste_23-02-17_19-44-47](https://user-images.githubusercontent.com/37923060/219645862-8799590c-a283-4181-8580-b28baa455c0c.png)

**Comment by twinkles-twinstar** [comment] 2023-02-20 15:37
The current version update has fixed the RTON codec logic error related to this issue, but this fix will not allow your RTON to be decoded, because there is a logic error in RTON (the byte count of the utf8 string is recorded with the string's actual bytes are not equal), tools will strictly treat it as exception RTON and throw an error.
The core logic of the tool only processes correct files, including RTON, PAM, RSB, etc. Any abnormal data will be regarded as an error and the processing of the program will be terminated, even if the game itself is fault-tolerant. This is the expected behavior of the tool and will not change in the future.
If you need to decode the RTON you provided, you should fix the exception structure first. The tool may provide a script to repair RTON in the future.

**Closed** 2023-02-20 15:37 UTC

**Comment by twinkles-twinstar** [comment] 2023-03-13 00:01
The new version has provided additional RTON lenient decoding function.

**Comment by Haruma-VN** [comment] 2023-03-13 00:05
Do I have to use JS Evaluate on it? Or just simply drag the RTON file directly to the tool?

**Comment by twinkles-twinstar** [comment] 2023-03-13 00:05
the latter
